export const ADOBE: { [char: string]: string | any } = {
  PLATFORM: "mobile website",
  DESKTOP_PLATFORM: "desktop website",

  TECHNOLOGY: "react",
  ASSET_TYPE: {
    PAYMENT: "payment",
    GLAMM_COINS: "Glammcoins",
    LOOKBOOK: "lookbook category",
    SEARCH: "search",
    HOME: "home",
    GLAMMSTUDIO: "glammstudio",
    REWARD_REFERRAL: "reward and referral",
    CHECKOUT_ADDRESS: "checkout address",
    PERSONALISED_LISTING_PAGE: "personalised listing page",
    MYGLAMMXO_SURVEY: "myglammxo survey",
    MYGLAMMXO: "myglammxo",
    MYGLAMMXO_QUIZ: "myglammxo quiz",
    EVENTS: "eventpage",
    WISHLIST: "wishlist",
    REMOVE_PRODUCT: "remove product",
    PDP: "product",
    ORDER_SUMMARY: "order summary",
    SHOPPING_BAG: "shopping bag",
    REFER: "reward and referral",
    MENU: "menu",
    HAMBURGER: "hamburger",
    TVC: "Shraddha Kapoor",
    TVC_SK_VIDEO: "Shraddha Kapoor video",
    FOCUS_GROUP: "Focus group",
    FOCUS_GROUP_SURVEY: "Focus Group Survey",
    ASK_ME_ANYTHING: "AskMeAnything",
    STORE_LOCATOR: "store locator",
    SHADE_FINDER: "shade finder",
    ST_BOTANICA_SURVEY: "stbotanicasurvey",
    FILMFARE: "Filmfare",
    SURVEY: {
      mgp: "myglammxo",
      stb: "stbotanicasurvey",
      bbc: "bbcsurvey",
      tmc: "tmcsurvey",
      orh: "orhsurvey",
      srn: "srnsurvey",
      popxo: "popxosurvey",
    },
    GOOD_POINTS: "good points",
    REWARD_CATALOG: "reward catalog",
    REWARD_DETAIL: "reward detail",
    REDEEM_SUCCESS: "reward redeem sucess",
    EARN_CATALOG: "earn catalog",
    PROFILE_BUILDER: "profile builder",
    LOGIN: "login",
    GP_LOGIN: "Good points login",
    GP_LANDING_PAGE: "good points landing page",
    REWARD_SUCCESS: "reward unlock sucess",
    APPLY_PC: "Apply Promo Code",
    CART_SUMMARY: "cart summary page",
    SLOT_MACHINE: "slot_machine",
    BIGG_BOSS: "bigg boss",
    ORDER_CHECKOUT_STEP_5: "order checkout step5",
    PAYMENT_SUCCESS: "payment success",
    SKIN_ANALYSER: "Skin Analyser",
    SKIN_ANALYSER_LANDING_PAGE: "Skin Analyser Landing Page",
    CTP_PLP: "cut the price product listing page",
    ORDER_RE_CONFIRMATION: "order re confirmation",
  },

  ADD_TO_BAG: {
    collection: {
      assetType: "collection",
      newAssetType: "collection",
      newLinkPageName: "collection ",
      linkPageName: "web|{productTag}|product listing page",
      linkName: "web|{category} - {name}|product listing page|ADD TO BAG",
    },
    product: {
      assetType: "product",
      newAssetType: "product",
      newLinkPageName: "product description",
      linkPageName: "web|{productTag}|product description page",
      linkName: "web|{category} - {name}|product description page|ADD TO BAG",
    },
    "shade-selection": {
      assetType: "product",
      newAssetType: "product",
      newLinkPageName: "product description",
      linkPageName: "web|{productTag}|product description page",
      linkName: "web|{category} - {name}|product description page|ADD TO BAG",
    },
    buy: {
      assetType: "category",
      newAssetType: "category",
      newLinkPageName: "category",
      linkPageName: "web|{productTag}|product listing page",
      linkName: "web|{category} - {name}|product listing page|ADD TO BAG",
    },
    glammstudio: {
      assetType: "blog",
      newAssetType: "content",
      newLinkPageName: "blog details",
      linkPageName: "web|glammstudio|blog",
      linkName: "web|glammstudio|blog|{name}|ADD TO BAG",
      blogName: "{blogName}",
    },
    looks: {
      assetType: "looks",
      newAssetType: "content",
      newLinkPageName: "look details",
      linkPageName: "web|glammstudio|looks",
      linkName: "web|glammstudio|looks|{name}|ADD TO BAG",
      lookName: "{lookName}",
    },
    tryon: {
      linkName: "web|tryon|ADD TO BAG",
      linkPageName: "web|tryon",
      ctaName: "add to bag-tryon",
      newLinkPageName: "product-tryon",
      subSection: `{category} - {subCategory}`,
      assetType: "tryon",
      newAssetType: "tryon",
    },
  },
};
