interface env {
  NEXT_PUBLIC_COMMUNITY_API_KEY?: string;
  NEXT_PUBLIC_SNOWPLOW_ENDPOINT?: string;
  NEXT_PUBLIC_TRUECALLER_APP_KEY?: string;
  NEXT_PUBLIC_SPJS_LINK?: string;
  NEXT_PUBLIC_BASE_URL?: string;
  NEXT_PUBLIC_RAZORPAY_KEY?: string;
  NEXT_PUBLIC_PRODUCT_ENV?: "ALPHA" | "PROD";
  NEXT_PUBLIC_FACEBOOK_PIXEL_KEY?: string;
  NEXT_PUBLIC_GTM_KEY?: string;
  NEXT_PUBLIC_GTM_KEY_AMP?: string;
  NEXT_PUBLIC_DATA_DOG_APP_ID?: string;
  NEXT_PUBLIC_DATA_DOG_CLIENT_TOKEN?: string;
  NEXT_PUBLIC_DATA_DOG_SERVICE?: string;
  NEXT_PUBLIC_DATA_DOG_ENV?: string;
  NEXT_PUBLIC_YELLOW_ID?: string;
  NEXT_PUBLIC_CANONICAL_BASE_URL?: string;
  NEXT_PUBLIC_OPT_CONTAINER_ID?: string;
  NEXT_PUBLIC_FIREBASE_API_KEY?: string;
  NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN?: string;
  NEXT_PUBLIC_FIREBASE_PROJECT_ID?: string;
  NEXT_PUBLIC_DOMAIN_URL?: string;
  NEXT_PUBLIC_ENABLE_HIT_LOGS?: boolean;
  NEXT_PUBLIC_ENABLE_DYN_REN?: boolean;
  NEXT_PUBLIC_ADOBE_REPORT_SUITE?: string;
  NEXT_PUBLIC_DATA_DOG_SAMPLE_RATE?: string;
  NEXT_PUBLIC_SSO_URL?: string;
  NEXT_PUBLIC_FINGERPRINT_KEY?: string;
  NEXT_PUBLIC_FINGERPRINT_API_KEY?: string;
  NEXT_PUBLIC_TRYON_KEY?: string;
  NEXT_PUBLIC_FLAGSMITH_ENV_ID?: string;
  NEXT_PUBLIC_PERFECT_CORP_API_KEY?: string;
  NEXT_PUBLIC_BBC_WORDPRESS_API?: string;
  NEXT_PUBLIC_WORDPRESS_URL?: string;
  NEXT_PUBLIC_AMP_ANALYTICS_SUBDOMAIN?: string;
}

export let GBC_ENV: env = {};

export const setENV = (env: env) => (GBC_ENV = env);
