import { SHOP } from "./SHOP.constant";
import { DUMMY_VENDOR_CODE } from "./DUMMY_VENDOR.constant";

/* As G3 generate env at runtine so need to declare xtoken everytime */
export const XTOKEN = () => `xtoken-${DUMMY_VENDOR_CODE() || SHOP.SITE_CODE}`;

export const LOCALSTORAGE = {
  UPSELL_DATA: "upsellData",
  SHIPPING_CHARGES: "shippingCharges",
  GIFT_CARD_PRODUCT: "giftCardProduct",
  IS_GIFT_CARD_ADDED_FROM_PAYMENT: "isGiftCardAddedFromPayment",
  USER_REMOVED_GIFT_CARD_MANUALLY: "userRemovedGiftCardManually",
  SHIPPING_ID: "shippingId",
  ORDER_BY_SEGMENT: "orderBySegment",
  MEMBER_ID: "memberId",
  SEARCHQUERIES: "searchQueries",
  STOKEN: "stoken",
  CARTID: "cartId",
  CORS_TOKEN: "cors-token",
  WISHLIST_ID: "wishlistId",
  IGNORE_DISCOUNT: "ignoreDiscountCode",
  COUPON: "coupon",
  GLAMMPOINTS: "gp",
  GUEST_DETAILS: "guestDetails",
  DISCOUNT_PRODUCT_ID: "discountTagProductId",
  ENABLE_COD: "enableCOD",
  ORDER_DETAILS: "orderDetails",
  PROFILE: "mgUserProfile",
  ADD_ADDRESS_FROM: "addAddressFrom",
  RESPONSE_SURVEY_ID: "responseSurveyId",
  GUEST_TOKEN: "guest-token",
  IS_GUEST: "isGuest",
  SURVEY_MEMBERTAG: "surveyMemberTag",
  WHATSAPP_ENABLED: "isWAEnabled",
  REFERRAL_CODE: "rc",
  AFFILIATE_VENDOR: "affiliate_vendor",
  UTM_PARAMS: "utmParams",
  SIMPL_TOKEN: "simplToken",
  GIFT_CARDS: "giftCards",
  FIRST_ORDER_FLAG: "isFirstOrder",
  G3_REWARD: "g3Reward",
  IS_SHIPPING_CHARGE_CASHBACK: "isShippingChargeCashBack",
  UPI_INTENT_FLOW_BANK_DETAILS: "upiIntentBankDetails",
  UPI_INTENT_APP_URL: "upiIntentAppUrl",
  ENABLE_WHATSAPP_OTP: "enableWhatsAppOtp",
  SLOT_MACHINE_RESPONSE_ID: "slotMachineResponseId",
  USER_SEGMENT: "userSegment",
  BEST_COUPON_AUTO_APPLIED: "bestCouponAutoApplied",
  CAPPING_DATA: "bannerCappingData",
  IS_SAVED_CARDS_PRESENT: "isSavedCardPresent",
  FUTURE_TIME: "futureTime",
  BIGG_BOSS_UPDATED: "biggBossUpdated",
  PARTNERSHIP_DATA: "partnershipData",
  PARTNERSHIP_PRODUCT_TAG: "partnershipProductTag",
  SKIN_ANALYSER_RESULTS: "skinAnalyserResults",
  IS_SHIPPING_ON_PAYMENT: "isShippingOnPayment",
  SHIPPING_CHARGES_ON_PAYMENT_VARIANT: "shippingChargesOnPaymentVariant",
  ORDER_CREATED_THROUGH_COD_PROMPT: "orderCreatedThroughCodPrompt",
  RECENT_PRODUCTS: "recentProduct",
  ONBOARD_COMMUNITY_POPUP_COUNT: "onboardCommunityPopupCount",
};

export const SESSIONSTORAGE = {
  GIFT_CARD_VARIANT: "giftCardVariant",
  SHIPPING_ID: "shippingId",
  CITY_ID: "cityId",
  WEBVIEW: "WV",
  TEMP_TOKEN: "tempToken",
  SURVEY_INFO: "surveyInfo",
  FB_EVENT_ID: "fbEventId",
  FREE_XO_PRODUCT: "freeXoProduct",
  AB_DYNAMIC_DISCOUNT_PRICE: "abDynamicDiscountPrice",
  CONTEST_SCROLL_POS_Y: "contestScrollPosition",
  PLP_SCROLL_POS_Y: "PLPScrollPosition",
  COMMUNITY_SCROLL_POS_Y: "COMMUNITY_SCROLL_POS_Y",
  TOPICS_SCROLL_POS_Y: "TOPICS_SCROLL_POS_Y",
  TAGS_SCROLL_POST_Y: "TAGS_SCROLL_POST_Y",
  PAYMENT_INITIATED_BY_SUGGESTED_PAYMENTS: "PAYMENT_INITIATED_BY_SUGGESTED_PAYMENTS",
  ONBOARD_COMMUNITY_POPUP: "showOnBoardpopupCommunity",
  COMMUNITY_TAB_CLICK: "communityTabClick",
  USER_LANDED_ON_OTHER_PAGES: "userLandedOnOtherPages",
  OFFLINE_STORE_NAME: "offlineStoreName",
  SKIN_ANALYSER_RESULTS: "skinAnalyserResults",
  PRODUCT_ADDED_FROM_UPSELL_PAYMENT: "productAddedFromUpsellPayment",
  HAS_USER_VISITED_CART_SUMMARY: "hasUserVisitedCartSummary",
  CB_POPUP_STATUS: "cbPopupStatus",
  GIFT_CARD_UPSELL_VARIANT: "giftCardUpsellVariant",
  TEMP_TRIAL_PRICE: "tempTrialPrice",
  WAREHOUSE_VARIANT: "warehouseVariant",
  UPSELL_COMBO_VARIANT: "upsellComboVariant",
  TRIAL_PRODUCT_SKU: "trialProductSKU",
  GIFT_CARD_PHASE_2_VARIANT: "giftCardPaymentPhase2",
  GUEST_PAYMENT_FLOW_VARIANT: "guestPaymentFlow",
  TEMP_LOGIN_DETAILS: "tempLoginDetail",
  ADDRESS_COUNTY_DETAILS: "addressCountyCode",
};

export const COOKIE = {
  MEMBERID_DS: "memberId_DS",
  USERNAME_DS: "userName_DS",
  COOKIETIME: 365,
  UTMPARAMS: "utmParams",
};
