export const WEBSITE_URL: any = {
  ALPHA: {
    mgp: "https://alpha-mr.myglamm.net",
    lit: "https://litbymyglamm.flashco.in",
    mnm: "https://manishmalhotramakeup.flashco.in",
    stb: "https://shop.staging.stbotanica.net",
    orb: "https://orientalbotanics.flashco.in",
    bbc: "https://shop.staging.babychakra.net",
    tmc: "https://shop.staging.themomsco.net",
    orh: "https://shop.staging.organicsharvest.net",
    srn: "https://shop.staging.thesirona.net",
    blu: "https://bleuofficial.flashco.in",
    popxo: "https://shop.staging.popxo.net",
    "srn-are": "https://shop.staging.thesirona.net/en-ae",
    "srn-sau": "https://shop.staging.thesirona.net/en-sa",
    "tmc-are": "https://shop.staging.themomsco.net/en-ae",
    "tmc-sau": "https://shop.staging.themomsco.net/en-sa",
  },
  PROD: {
    mgp: "https://www.myglamm.com",
    lit: "https://litbymyglamm.com",
    mnm: "https://www.manishmalhotramakeup.com",
    stb: "https://www.stbotanica.com",
    orb: "https://orientalbotanics.com",
    bbc: "https://www.babychakra.com",
    tmc: "https://themomsco.com",
    orh: "https://www.organicharvest.in",
    srn: "https://www.thesirona.com",
    blu: "https://bleuofficial.com",
    popxo: "https://shop.popxo.com",
    "srn-are": "https://www.thesirona.com/en-ae",
    "srn-sau": "https://www.thesirona.com/en-sa",
    "tmc-are": "https://themomsco.com/en-ae",
    "tmc-sau": "https://themomsco.com/en-sa",
  },
};
