export const SHARE_URLS = [
  {
    url: "https://www.facebook.com/sharer/sharer.php?u={shareURL}",
    name: "facebook",
    icon: "https://files.myglamm.com/site-images/original/facebook-app-symbol.png",
  },
  {
    url: "https://twitter.com/intent/tweet?text=={shareURL}",
    name: "twitter",
    icon: "https://files.myglamm.com/site-images/original/81609.png",
  },
  {
    url: "http://pinterest.com/pin/create/button/?url={shareURL}",
    name: "pinterest",
    icon: "https://files.myglamm.com/site-images/original/pinterest.png",
  },
];

export const OrderStatuses: any = {
  0: { name: "Inactive", label: "Inactive" },
  1: { name: "Active", label: "Active" },
  3: { name: "Delete", label: "Delete" },
  10: { name: "FutureOrder", label: "Future_Order" },
  11: { name: "Pending", label: "Pending" },
  12: { name: "Confirmed", label: "Confirmed" },
  13: { name: "Cancelled", label: "Cancelled" },
  14: { name: "InTransit", label: "Shipped" },
  15: { name: "Completed", label: "Delivered" },
  16: { name: "Expired", label: "Expired" },
  17: { name: "ReturnInitiated", label: "Return Initiated" },
  18: { name: "ReturnCompleted", label: "Return Completed" },
  19: { name: "ReturnToOrigin", label: "Return To Origin" },
  20: { name: "PendingApproval", label: "Pending Approval" },
  21: { name: "PaymentPending", label: "PaymentPending" },
  22: { name: "PaymentPGInitiated", label: "PaymentPG-initiated" },
  23: { name: "PaymentPaid", label: "PaymentPaid" },
  24: { name: "PaymentCancelled", label: "PaymentCancelled" },
  25: { name: "PaymentRefundIntiated", label: "PaymentRefund-intiated" },
  26: { name: "PaymentRefunded", label: "PaymentRefunded" },
  27: { name: "PaymentFailed", label: "PaymentFailed" },
  28: { name: "PaymentRefundFailed", label: "PaymentRefundFailed" },
  31: { name: "Draft", label: "Draft" },
  32: { name: "Published", label: "Published" },
  33: { name: "Trash", label: "Trash" },
  41: { name: "PromoPending", label: "PromoPending" },
  42: { name: "PromoRedeemed", label: "PromoRedeemed" },
  43: { name: "PromoReverted", label: "PromoReverted" },
  61: { name: "GiftcardPending", label: "GiftcardPending" },
  62: { name: "GiftcardCompleted", label: "GiftcardCompleted" },
  63: { name: "GCPaymentPending", label: "GCPaymentPending" },
  64: { name: "GCPaymentPGInitiated", label: "GCPaymentPGInitiated" },
  65: { name: "GCPaymentFailed", label: "GCPaymentFailed" },
  66: { name: "GCPaymentPaid", label: "GCPaymentPaid" },
  71: { name: "Reject", label: "Reject" },
  72: { name: "PreOrdered", label: "Pre Ordered" },
  73: { name: "Partial", label: "Partial" },
  74: { name: "ReadyToShip", label: "Ready To Ship" },
  75: { name: "OutForDelivery", label: "Out For Delivery" },
  76: { name: "Packing", label: "Packing" },
  77: { name: "Picking", label: "Picking" },
  78: { name: "Hold", label: "Hold" },
  79: { name: "WMSClosed", label: "Closed" },
  80: { name: "Invoicing", label: "Invoicing" },
  81: { name: "Failed", label: "failed" },
  82: { name: "Replaced", label: "Replaced" },
  83: { name: "Processing", label: "Processing" },
  84: { name: "Allocated", label: "Allocated" },
  86: { name: "Fraud", label: "Fraud" },
  87: { name: "CommissionProcessing", label: "CommissionProcessing" },
  88: { name: "CommissionAvailed", label: "CommissionAvailed" },
  89: { name: "CommissionPending", label: "CommissionPending" },
  90: { name: "CommissionRevert", label: "CommissionRevert" },
  91: { name: "Accepted", label: "Accepted" },
};

export const USER_TABS = [
  { label: "myAddresses", fallback: "my addresses" },
  { label: "personalInfo", fallback: "personal info" },
  { label: "notificationSett", fallback: "notification settings" },
];
